import axios from 'axios';

class YouTubeService {
    constructor() {
        this.apiKey = process.env.YOUTUBE_API_KEY;
        this.baseUrl = 'https://www.googleapis.com/youtube/v3';
    }

    /**
     * Searches YouTube for a highly concise, educational video
     * @param {string} query - The search term generated by Gemini
     * @returns {string|null} - The YouTube Video ID
     */
    async searchVideo(query) {
        if (!this.apiKey) {
            console.warn('[YouTubeService] YOUTUBE_API_KEY is not defined. Skipping video fetch.');
            return null;
        }

        try {
            console.log(`[YouTubeService] Searching for: "${query}"`);

            const response = await axios.get(`${this.baseUrl}/search`, {
                params: {
                    part: 'snippet',
                    maxResults: 1,
                    q: `${query} crash course explanation`, // Appending terms to bias towards educational content
                    type: 'video',
                    videoEmbeddable: 'true',
                    relevanceLanguage: 'en',
                    key: this.apiKey,
                },
            });

            if (response.data && response.data.items && response.data.items.length > 0) {
                const videoId = response.data.items[0].id.videoId;
                console.log(`[YouTubeService] Found video ID: ${videoId}`);
                return videoId;
            }

            console.log(`[YouTubeService] No videos found for query: ${query}`);
            return null;

        } catch (error) {
            console.error('[YouTubeService] Error fetching from YouTube Data API:', error?.response?.data || error.message);
            // Don't crash the lesson generation if YT fails, just return null
            return null;
        }
    }
}

export default new YouTubeService();
